version: '3'
services: 
    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        networks: 
            - broker-kafka
        environment:
            # Instructs ZooKeeper where to listen for connections by clients
            ZOOKEEPER_CLIENT_PORT: 2181
            # The basic time unit in milliseconds used by ZooKeeper
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
        image: confluentinc/cp-kafka:latest
        networks: 
            - broker-kafka
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    interface:
        build: .
        ports: 
            - 8000:8000
        environment: 
            KAFKA_HOSTS: kafka:29092
            REDIS_HOST: redis
            REDIS_PORT: 6379    
        networks: 
            - broker-kafka
        depends_on: 
            - kafka        
            - redis
networks: 
    broker-kafka:
        driver: bridge  