version: '3.7'

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        env_file:
            - .env
        restart: always
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        env_file:
            - .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper
        restart: always
    web_server:
        build:
            context: .
            dockerfile: ./docker/web_server/Dockerfile
        volumes:
            - static_volume:/home/django/C01/staticfiles
            - data:/data
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - kafka
        restart: on-failure
    link_generator:
        build: 
            context: .
            dockerfile: ./docker/link_generator/Dockerfile
        env_file:
            - .env
        depends_on: 
            - kafka
            - redis
        restart: on-failure
    spider_manager:
        build: 
            context: .
            dockerfile: ./docker/spider_manager/Dockerfile
        env_file:
            - .env
        depends_on: 
            - kafka
            - redis 
        restart: on-failure
    writer:
        build:
            context: .
            dockerfile: ./docker/writer/Dockerfile
        volumes:
            - data:/data
        env_file:
            - .env
        depends_on:
            - kafka
        restart: on-failure

volumes:
    static_volume:
    data:
    postgres_data:
