version: '3'

services:     
    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        restart: always

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_ADVERTISED_HOST_NAME: kafka
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper
        restart: always
    
    spider_manager:
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - kafka
            - redis
            - zookeeper
        environment: 
            - KAFKA_HOSTS: kafka:9092 
            - COMMANDS_TOPIC: 'spider_manager-commands'
        restart: always
