# [NÂO FUNCIONA]

version: '3'

services:     
    spider_manager:
        depends_on: 
            - kafka
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile
    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        restart: always
    kafka:
        image: wurstmeister/kafka:2.11-2.0.1
        ports:
            - "9092:9092"
            - "9093:9093"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper
        restart: always