# Generated by Django 3.2.12 on 2022-04-06 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('source_name', models.CharField(max_length=200)),
                ('base_url', models.TextField()),
                ('obey_robots', models.BooleanField(blank=True, null=True)),
                ('data_path', models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\/\\\\-_]*$', 'This is not a valid path.')])),
                ('request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=15)),
                ('form_request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=15)),
                ('antiblock_download_delay', models.IntegerField(blank=True, null=True)),
                ('antiblock_autothrottle_enabled', models.BooleanField(blank=True, default=False)),
                ('antiblock_autothrottle_start_delay', models.IntegerField(blank=True, null=True)),
                ('antiblock_autothrottle_max_delay', models.IntegerField(blank=True, null=True)),
                ('antiblock_ip_rotation_enabled', models.BooleanField(blank=True, default=False)),
                ('antiblock_ip_rotation_type', models.CharField(blank=True, max_length=15, null=True)),
                ('antiblock_max_reqs_per_ip', models.IntegerField(blank=True, null=True)),
                ('antiblock_max_reuse_rounds', models.IntegerField(blank=True, null=True)),
                ('antiblock_proxy_list', models.TextField(blank=True, null=True)),
                ('antiblock_user_agent_rotation_enabled', models.BooleanField(blank=True, default=False)),
                ('antiblock_reqs_per_user_agent', models.IntegerField(blank=True, null=True)),
                ('antiblock_user_agents_list', models.TextField(blank=True, null=True)),
                ('antiblock_insert_cookies_enabled', models.BooleanField(blank=True, default=False)),
                ('antiblock_cookies_list', models.TextField(blank=True, null=True)),
                ('captcha', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('sound', 'Sound')], default='none', max_length=15)),
                ('has_webdriver', models.BooleanField(blank=True, null=True)),
                ('webdriver_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_xpath', models.CharField(blank=True, max_length=100, null=True)),
                ('sound_xpath', models.CharField(blank=True, max_length=100, null=True)),
                ('dynamic_processing', models.BooleanField(blank=True, null=True)),
                ('explore_links', models.BooleanField(blank=True, null=True)),
                ('link_extractor_max_depth', models.IntegerField(blank=True, null=True)),
                ('link_extractor_allow_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_extractor_allow_domains', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_extractor_tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_extractor_attrs', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_extractor_check_type', models.BooleanField(blank=True, null=True)),
                ('link_extractor_process_value', models.TextField(blank=True, max_length=1000, null=True)),
                ('download_files', models.BooleanField(blank=True, null=True)),
                ('download_files_allow_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('download_files_allow_extensions', models.CharField(blank=True, max_length=2000, null=True)),
                ('download_files_allow_domains', models.CharField(blank=True, max_length=1000, null=True)),
                ('download_files_tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('download_files_attrs', models.CharField(blank=True, max_length=1000, null=True)),
                ('download_files_process_value', models.TextField(blank=True, max_length=1000, null=True)),
                ('download_files_check_large_content', models.BooleanField(blank=True, default=True, null=True)),
                ('download_imgs', models.BooleanField(default=False)),
                ('steps', models.CharField(blank=True, default='{}', max_length=9999999, null=True)),
                ('encoding_detection_method', models.IntegerField(choices=[(1, 'Via cabeçalho da resposta'), (2, 'Automático')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection_type', models.CharField(choices=[('templated_url', 'Templated URL'), ('static_form', 'Static Form')], default='none', max_length=15)),
                ('handler_type', models.CharField(choices=[('text', 'Texto na página'), ('http_status', 'Código de status HTTP'), ('binary', 'Arquivo de tipo binário')], max_length=15)),
                ('text_match_value', models.CharField(blank=True, max_length=1000)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('opposite', models.BooleanField(default=False)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_handlers', to='main.crawlrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection_type', models.CharField(choices=[('templated_url', 'Templated URL'), ('static_form', 'Static Form')], default='none', max_length=15)),
                ('parameter_key', models.CharField(blank=True, max_length=1000)),
                ('parameter_label', models.CharField(blank=True, max_length=1000)),
                ('filter_range', models.BooleanField(default=False)),
                ('cons_misses', models.PositiveIntegerField(blank=True, null=True)),
                ('parameter_type', models.CharField(choices=[('number_seq', 'Sequência numérica'), ('date_seq', 'Sequência de datas'), ('alpha_seq', 'Sequência alfabética'), ('process_code', 'Código de processo'), ('value_list', 'Lista pré-definida'), ('const_value', 'Valor constante')], default='none', max_length=15)),
                ('first_year_proc_param', models.PositiveIntegerField(blank=True, null=True)),
                ('last_year_proc_param', models.PositiveIntegerField(blank=True, null=True)),
                ('segment_ids_proc_param', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator('^(\\s*[0-9]+\\s*,)*\\s*[0-9]+\\s*$', 'Insira uma lista de números separados por vírgula.')])),
                ('court_ids_proc_param', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator('^(\\s*[0-9]+\\s*,)*\\s*[0-9]+\\s*$', 'Insira uma lista de números separados por vírgula.')])),
                ('origin_ids_proc_param', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator('^(\\s*[0-9]+\\s*,)*\\s*[0-9]+\\s*$', 'Insira uma lista de números separados por vírgula.')])),
                ('first_num_param', models.IntegerField(blank=True, null=True)),
                ('last_num_param', models.IntegerField(blank=True, null=True)),
                ('step_num_param', models.IntegerField(blank=True, null=True)),
                ('leading_num_param', models.BooleanField(default=False)),
                ('length_alpha_param', models.PositiveIntegerField(blank=True, null=True)),
                ('num_words_alpha_param', models.PositiveIntegerField(blank=True, null=True)),
                ('no_upper_alpha_param', models.BooleanField(default=False)),
                ('date_format_date_param', models.CharField(blank=True, max_length=1000)),
                ('start_date_date_param', models.DateField(blank=True, null=True)),
                ('end_date_date_param', models.DateField(blank=True, null=True)),
                ('frequency_date_param', models.CharField(choices=[('Y', 'Anual'), ('M', 'Mensal'), ('D', 'Diária')], default='D', max_length=15)),
                ('value_const_param', models.CharField(blank=True, max_length=5000)),
                ('value_list_param', models.CharField(blank=True, max_length=50000)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_handlers', to='main.crawlrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerInstance',
            fields=[
                ('creation_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('instance_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('running', models.BooleanField()),
                ('crawler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='main.crawlrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
