# Generated by Django 3.2.1 on 2021-05-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('log_message', models.CharField(blank=True, max_length=2000, null=True)),
                ('logger_name', models.CharField(blank=True, max_length=50, null=True)),
                ('log_level', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_log', models.CharField(blank=True, max_length=5000, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='main.crawlerinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
