# Generated by Django 3.2.12 on 2022-04-06 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_crawlers_running', models.PositiveIntegerField(blank=True, default=5)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerQueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('running', models.BooleanField(blank=True, default=False)),
                ('crawl_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.crawlrequest', unique=True)),
                ('queue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.crawlerqueue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
