# Generated by Django 3.1.3 on 2020-11-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='crawler_type',
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='dynamic_processing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
