# Generated by Django 3.0.7 on 2020-09-17 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='data',
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='data_path',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\/\\\\-_]*$', 'This is not a valid path.')]),
        ),
    ]
