# Generated by Django 3.2 on 2021-05-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210505_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='dynamic_processing',
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='crawler_type',
            field=models.CharField(choices=[('static_page', 'Static Page'), ('form_page', 'Page with Form'), ('single_file', 'Single File'), ('bundle_file', 'Bundle File')], default='static_page', max_length=15),
        ),
    ]
