# Generated by Django 3.0.6 on 2020-05-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crawlrequest_antiblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='captcha',
            field=models.CharField(choices=[('1', 'None'), ('2', 'Image'), ('3', 'Sound')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='crawlrequest',
            name='antiblock',
            field=models.CharField(choices=[('1', 'None'), ('2', 'IP rotation'), ('3', 'User-agent rotation'), ('4', 'Random delays'), ('5', 'Use proxy'), ('6', 'Use cookies')], default='1', max_length=15),
        ),
    ]
