# Generated by Django 3.0.6 on 2020-05-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200521_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='antiblock',
        ),
    ]
