# Generated by Django 3.2 on 2021-05-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210514_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_attrs',
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_attributes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_decimal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_displayed_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_encoding',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_flavor',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_header',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_index_col',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_keep_default_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_match',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_na_values',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_parse_dates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_skiprows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_thousands',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='crawlrequest',
            name='save_csv',
            field=models.BooleanField(default=True),
        ),
    ]
