# Generated by Django 3.0.6 on 2020-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_crawlrequest_antiblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='antiblock',
            field=models.CharField(choices=[('none', 'None'), ('ip', 'IP rotation'), ('user_agent', 'User-agent rotation'), ('delay', 'Delays'), ('cookies', 'Use cookies')], default='none', max_length=15),
        ),
    ]
