# Generated by Django 3.2 on 2021-05-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210515_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_attributes',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_decimal',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_displayed_only',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_encoding',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_flavor',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_header',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_index_col',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_keep_default_na',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_match',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_na_values',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_parse_dates',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_skiprows',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='table_thousands',
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='table_attrs',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='crawlrequest',
            name='save_csv',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
