# Generated by Django 2.2.12 on 2020-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200608_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='user_agents_file',
            field=models.FileField(blank=True, max_length=20, null=True, upload_to=None),
        ),
    ]
