# Generated by Django 2.2.12 on 2020-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200609_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='tor_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
