# Generated by Django 2.2.12 on 2020-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200609_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='user_agents_file',
            field=models.FileField(blank=True, max_length=20, null=True, upload_to='files/user_agent_files'),
        ),
    ]
