# Generated by Django 2.2.12 on 2020-06-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200609_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='tor_password',
        ),
    ]
