# Generated by Django 2.2.12 on 2020-06-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_crawlrequest_tor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='cookies_file',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='crawlrequest',
            name='proxy_list',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='crawlrequest',
            name='user_agents_file',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
