# Generated by Django 2.2.12 on 2020-06-10 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200609_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
