# Generated by Django 2.2.12 on 2020-06-10 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200610_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
