# Generated by Django 2.2.12 on 2020-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200610_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='crawler_type',
            field=models.CharField(choices=[('static_page', 'Static Page'), ('form_page', 'Page with Form'), ('single_file', 'Single File'), ('bundle_file', 'Bundle File')], default='static_page', max_length=15),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='explore_links',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='link_extractor_allow',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='link_extractor_max_depht',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crawlrequest',
            name='captcha',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('sound', 'Sound')], default='none', max_length=15),
        ),
    ]
