# Generated by Django 2.2.12 on 2020-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200612_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlrequest',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='sound_url',
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='has_webdriver',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='webdriver_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
