# Generated by Django 2.2.12 on 2020-06-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200615_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('instance_id', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField()),
                ('running', models.BooleanField()),
                ('crawler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CrawlRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
