# Generated by Django 2.2.12 on 2020-06-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200617_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlerinstance',
            name='started_at',
        ),
    ]
