# Generated by Django 2.2.12 on 2020-06-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200617_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerinstance',
            name='crawler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CrawlRequest', unique=True),
        ),
        migrations.AlterField(
            model_name='crawlerinstance',
            name='instance_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
