# Generated by Django 2.2.12 on 2020-06-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200617_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerinstance',
            name='crawler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CrawlRequest'),
        ),
        migrations.AlterField(
            model_name='crawlerinstance',
            name='instance_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
