# Generated by Django 3.0.7 on 2020-06-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200617_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
