# Generated by Django 2.2.12 on 2020-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_crawlrequest_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='link_extractor_allow_extensions',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
