# Generated by Django 2.2.12 on 2020-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200624_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='cookies_file',
            new_name='antiblock_cookies_file',
        ),
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='delay_secs',
            new_name='antiblock_download_delay',
        ),
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='ip_type',
            new_name='antiblock_ip_rotation_type',
        ),
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='max_reqs_per_ip',
            new_name='antiblock_max_reqs_per_ip',
        ),
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='max_reuse_rounds',
            new_name='antiblock_max_reuse_rounds',
        ),
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='persist_cookies',
            new_name='antiblock_persist_cookies',
        ),
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='proxy_list',
            new_name='antiblock_proxy_list',
        ),
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='reqs_per_user_agent',
            new_name='antiblock_reqs_per_user_agent',
        ),
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='user_agents_file',
            new_name='antiblock_user_agents_file',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='antiblock',
        ),
        migrations.RemoveField(
            model_name='crawlrequest',
            name='delay_type',
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='antiblock_autothrottle_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='antiblock_autothrottle_max_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='antiblock_autothrottle_start_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='antiblock_mask_type',
            field=models.CharField(choices=[('none', 'None'), ('ip', 'IP rotation'), ('user_agent', 'User-agent rotation'), ('cookies', 'Use cookies')], default='none', max_length=15),
        ),
    ]
