# Generated by Django 3.0.8 on 2020-08-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200703_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='steps',
            field=models.CharField(default={}, max_length=9999999),
        ),
    ]
