# Generated by Django 3.0.3 on 2020-07-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200703_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlrequest',
            old_name='antiblock_user_agents_file',
            new_name='antiblock_user_agents',
        ),
    ]
