# Generated by Django 3.0.8 on 2020-08-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200703_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='output_filename',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='save_csv',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
