# Generated by Django 3.0.8 on 2020-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_crawlrequest_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='steps',
            field=models.CharField(default='\\{\\}', max_length=9999999),
        ),
    ]
