# Generated by Django 3.0.8 on 2020-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_crawlrequest_output_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='output_path',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
