# Generated by Django 3.0.8 on 2020-08-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200824_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='output_path',
            field=models.FilePathField(blank=True, max_length=2000, null=True, path='/home'),
        ),
    ]
