# Generated by Django 3.0.8 on 2020-07-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200721_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerinstance',
            name='collected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerinstance',
            name='scheduled',
            field=models.IntegerField(default=0),
        ),
    ]
