# Generated by Django 3.0.8 on 2020-08-25 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200825_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='output_path',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\/\\\\-_]*$', 'This is not a valid path.')]),
        ),
    ]
