version: '3.7'

services:
  web:
    build:
      context: ..
      dockerfile: ./docker-web/django-gunicorn.Dockerfile
    # TODO Change to use gunicorn directly when FileDescriptor is dockerized
    command: ./temp_run.sh
    environment:
      - EXECUTION_TYPE=distributed
    volumes:
      - static_volume:/home/django/C01/staticfiles
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build:
      context: ..
      dockerfile: ./docker-web/nginx.Dockerfile
    volumes:
      - static_volume:/home/nginx/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    hostname: localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    ports:
      - "5432:5432"

volumes:
  static_volume:
  postgres_data:
